language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python manage.py behave
deploy:
  provider: heroku
  api_key:
    secure: rtejn4sesAlIkZBJ7oaTJMBpaRCTumzy46OHi/1j3Fz3MHTvfX3PsjdvXskrInu5SFF2z7pqPhkzZmsvltgFRJZjirnp0Gv7swvZnGOswrPSSMD5013GAmMDe9KAUbS6lrnqd0PRNFH/FZ/SzVhc8UYUHo0G3cLfO2WYY7M3+j71eNPUIL3zhUbEfqEXOgGGOiPtj3L/t7eLTv4Pim1EJvoyXwnDigcFZYdCQPNTqrXXDaUXgl2H0Keat3kXXaZk28HBMOpcf4m7Th3Tj7+eseEWUuEfKBJX/0ZlIGWLwzik1lb+DG0+s21r73kEl3fr6cDvZXF09haPDJ68OLDw/O5fANlRaRwB+aZo+Hb6KHdSGfN8O1GQ4rtjGOfkZzV5iFc2D6bCqcMzZepzbCC3XaiL1bLx3W+aXpethfxvRTwzDDA9BfU0ohjHMvF1rDc9wJyGFCoWIFur+aNWeR1/bu/9RIzOS9bFNLLUkHEbkW0tPj5/qX49pwPyE3hedJfn6fSgmYulbHYxJQPhR+SN7N1NwTGwBqWBz+VQZuY2shNcZikCpg9Of6faqaf7/6A/A5z8O7ZiW6bLNb6nBzdRXB9EG4zRMu5tQXXgcY3SWzQAj3KXt2PE5v5LEOxLsclHxWLAtXeib8exa9fVTusoLMoQDulG8EqRbOFHdUH/AJ4=
  app: trazdia
  on:
    repo: JaTvoiRabotnik/trazdia
